import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Movie Ticket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="wrap">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
